let allowInitialData = false;
let editControlsActive = [];

const initialDescriptions = [
    {
      name: '',
      descriptionsInBlock: 9
    },
    [ 'Inicio del día',
      ['', 'Baño'],
     ['', 'Desayuno'],
     ['', 'Noticias'],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', '' ]],
    [ 'Actividades',
     ['', 'Trabajo'],
     ['', 'Programación'],
     ['', 'Compras'],
     ['', 'Reuniones'],
     ['', 'Llamadas'],
     ['', '' ]],
    [ 'Tarde',
     ['', 'Deporte'],
     ['', 'Matemáticas'],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', '' ]],
    [ 'Final del día',
     ['', 'Lectura'],
     ['', 'Inglés'],
     ['', 'Guitarra'],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', ''],
     ['', '' ]]
  ];